version: "3.9"
services:
  # Apache a PHP
  www:
    build: ./docker/php-apache # cesta k Dockerfile
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8080:80

  # MySQL databáze
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor # nastavení hesla pro uživatele root

  # administrace databáze
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8081:8080